name: $(Date:yyyyMMdd)$(Rev:.r)-ArgoCD
trigger: none
pr: none

variables:
  AWS_SERVICE_CONNECTION: 'bahi-aws-v2'
  AWS_REGION: 'us-east-1'
  CLUSTER_NAME: 'eks-platform-nonprod-v2-cluster'

pool:
  name: queue-bebo_mohammed

jobs:
- job: ArgoSync
  displayName: 'ArgoCD Sync / Rollout'
  steps:
  - checkout: self

  - task: AWSShellScript@1
    displayName: Configure kubeconfig
    inputs:
      awsCredentials: $(AWS_SERVICE_CONNECTION)
      regionName: $(AWS_REGION)
      scriptType: inline
      inlineScript: |
        set -euo pipefail
        
        if [ -z "$(CLUSTER_NAME)" ]; then
          echo "Error: CLUSTER_NAME variable is not set."
          exit 1
        fi

        echo "Checking if cluster $(CLUSTER_NAME) exists..."
        if ! aws eks describe-cluster --name "$(CLUSTER_NAME)" --region "$(AWS_REGION)" >/dev/null 2>&1; then
           echo "##[warning]Cluster $(CLUSTER_NAME) not found. Skipping kubeconfig setup."
           echo "##vso[task.setvariable variable=CLUSTER_EXISTS]false"
           exit 0
        fi

        echo "Connecting to cluster: $(CLUSTER_NAME)..."
        aws eks update-kubeconfig --name "$(CLUSTER_NAME)" --region "$(AWS_REGION)"
        
        # Get API Gateway URL for ingress annotations
        APIGW_URL=$(aws apigatewayv2 get-apis --query "Items[?Name=='eks-platform-nonprod-v2-api-v2-nonprod'].ApiEndpoint" --output text)
        echo "Found API Gateway: $APIGW_URL"
        echo "##vso[task.setvariable variable=APIGW_URL]$APIGW_URL"
        echo "##vso[task.setvariable variable=CLUSTER_EXISTS]true"

  - task: Docker@2
    displayName: Docker Login
    inputs:
      command: login
      containerRegistry: 'docker'

  - task: Bash@3
    displayName: Export Docker Credentials
    inputs:
      targetType: inline
      script: |
        DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
        CONFIG_FILE="$DOCKER_CONFIG/config.json"
        AUTH_STRING=$(python3 -c "import json; data = json.load(open('$CONFIG_FILE')); print(list(data['auths'].values())[0]['auth'])")
        DECODED_AUTH=$(echo "$AUTH_STRING" | base64 -d)
        DOCKER_USERNAME=$(echo "$DECODED_AUTH" | cut -d: -f1)
        DOCKER_PASSWORD=$(echo "$DECODED_AUTH" | cut -d: -f2-)
        echo "##vso[task.setvariable variable=DOCKER_USERNAME]$DOCKER_USERNAME"
        echo "##vso[task.setvariable variable=DOCKER_PASSWORD;isSecret=true]$DOCKER_PASSWORD"

  - task: AWSShellScript@1
    displayName: Deploy Motivational App (Helm)
    inputs:
      awsCredentials: $(AWS_SERVICE_CONNECTION)
      regionName: $(AWS_REGION)
      scriptType: inline
      inlineScript: |
        set -euo pipefail
        
        if [ "$(CLUSTER_EXISTS)" == "false" ]; then
           exit 0
        fi

        kubectl delete secret regcred -n bahi --ignore-not-found=true
        kubectl create secret docker-registry regcred \
          --namespace bahi \
          --docker-server=https://index.docker.io/v1/ \
          --docker-username="$(DOCKER_USERNAME)" \
          --docker-password="$(DOCKER_PASSWORD)" \
          --docker-email=bebomohammed904@gmail.com
        
        if ! command -v helm &> /dev/null; then
            curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        fi

        # Create values file using printf to avoid YAML/Shell parsing issues
        printf "ingress:\n  annotations:\n    nginx.ingress.kubernetes.io/auth-signin: \"$(APIGW_URL)/oauth2/start?rd=\$escaped_request_uri\"\n" > dynamic-values.yaml

        helm upgrade --install motivational-app ./motivational-app \
          --namespace bahi --create-namespace \
          --set image.tag="latest" \
          -f dynamic-values.yaml \
          --wait --timeout 10m \
          --debug

        kubectl rollout restart deployment -n bahi -l app.kubernetes.io/instance=motivational-app
    env:
      DOCKER_PASSWORD: $(DOCKER_PASSWORD)
