name: $(Date:yyyyMMdd)$(Rev:.r)-ArgoCD
trigger: none
pr: none

variables:
  AWS_SERVICE_CONNECTION: 'bahi-aws-v2'
  AWS_REGION: 'us-east-1'
  # OPTIMIZATION: We assume CLUSTER_NAME is provided as a pipeline variable
  CLUSTER_NAME: 'eks-platform-nonprod-v2-cluster'

# pool:
#   vmImage: ubuntu-latest

pool:
 name: queue-bebo_mohammed

jobs:
- job: ArgoSync
  displayName: 'ArgoCD Sync / Rollout'
  steps:
  - checkout: self

  # 1. Configure Kubeconfig directly using the Variable (No Terraform needed)
  - task: AWSShellScript@1
    displayName: Configure kubeconfig
    inputs:
      awsCredentials: $(AWS_SERVICE_CONNECTION)
      regionName: $(AWS_REGION)
      scriptType: inline
      inlineScript: |
        set -euo pipefail
        
        if [ -z "$(CLUSTER_NAME)" ]; then
          echo "Error: CLUSTER_NAME variable is not set."
          echo "Please set 'CLUSTER_NAME' in your Pipeline Variables (e.g. realfinal-eks)."
          exit 1
        fi

        echo "Checking if cluster $(CLUSTER_NAME) exists..."
        if ! aws eks describe-cluster --name "$(CLUSTER_NAME)" --region "$(AWS_REGION)" >/dev/null 2>&1; then
           echo "##[warning]Cluster $(CLUSTER_NAME) not found. Skipping kubeconfig setup."
           echo "##vso[task.setvariable variable=CLUSTER_EXISTS]false"
           exit 0
        fi

        echo "Connecting to cluster: $(CLUSTER_NAME)..."
        aws eks update-kubeconfig --name "$(CLUSTER_NAME)" --region "$(AWS_REGION)"
        echo "##vso[task.setvariable variable=CLUSTER_EXISTS]true"

  # 2. Deploy/Update Motivational App
  - task: AWSShellScript@1
    displayName: Deploy Motivational App (Helm)
    inputs:
      awsCredentials: $(AWS_SERVICE_CONNECTION)
      regionName: $(AWS_REGION)
      scriptType: inline
      inlineScript: |
        set -euo pipefail
        
        if [ "$(CLUSTER_EXISTS)" == "false" ]; then
           echo "Cluster does not exist. Skipping deployment."
           exit 0
        fi
        
        # Ensure Helm is installed (if not already by previous stages, but good to be safe/consistent)
        if ! command -v helm &> /dev/null; then
            echo "Installing Helm..."
            curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        fi

        echo "Deploying Motivational App..."
        # Using the motivational-app chart we created
        # Injecting the BuildId as the image tag so it pulls the artifacts built in Release Pipeline
        
        # Check for stuck release and rollback if necessary
        if helm status motivational-app -n default | grep -q 'pending-'; then
            echo "Release is stuck in pending state. Rolling back..."
            helm rollback motivational-app -n default || true
        fi
        
        helm upgrade --install motivational-app ./motivational-app \
          --namespace default \
          --set image.tag="$(Build.BuildId)" \
          --wait --timeout 5m \
          --atomic

        echo "Forcing restart of application deployment to ensure latest image..."
        # The chart creates a deployment named 'simple-web-app' (from values.yaml fullnameOverride)
        kubectl rollout restart deployment/simple-web-app -n default
        
        echo "Checking rollout status..."
        kubectl rollout status deployment/simple-web-app -n default
