name: $(Date:yyyyMMdd)$(Rev:.r)-Release
trigger: none

pr: none

variables:
  AWS_SERVICE_CONNECTION: 'bahi-aws-v2'
  AWS_REGION: 'us-east-1'
  IMAGE_REPOSITORY: '20107946/realfinal'
  # OPTIMIZATION: Set this variable in Azure DevOps Library to avoid running Terraform to find it.
  # CLUSTER_NAME: 'realfinal-eks' 
# pool:
#  vmImage: ubuntu-latest
pool:
  name: queue-bebo_mohammed

jobs:
- job: Release
  displayName: 'Build and Release Docker Image'
  pool:
    name: queue-bebo_mohammed
  steps:
  - checkout: self

  # 1. Build and Push (Does not need Cluster Access)
  - task: Docker@2
    displayName: Build and Push Docker Image
    inputs:
      containerRegistry: 'docker'
      repository: 20107946/realfinal
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(Build.BuildId)
        latest

  # 2. Deploy via Kubectl (Optional - only if you want to force update without ArgoCD)
  # Keeping this simple: Release just builds. ArgoCD Pipeline handles the rest.
